import = [
  # "~/.config/alacritty/themes/themes/tokyonight_night.toml"
  "~/.config/alacritty/themes/themes/solarized_osaka.toml",
]

[env]
TERM = 'xterm-256color'

[window]
padding.x = 5
padding.y = 5
dimensions.columns = 140
dimensions.lines = 35

position.x = 100
position.y = 100
decorations = "Buttonless"
opacity = 0.86
blur = true

[font]
normal = { family = "VictorMono Nerd Font Propo" }
size = 18

[colors]
vi_mode_cursor.text = "CellBackground"
vi_mode_cursor.cursor = "CellForeground"
