import = [
#	"~/.config/alacritty/themes/themes/nightfox.toml"
#	"~/.config/alacritty/themes/themes/nordfox.toml"
"~/.config/alacritty/themes/themes/duskfox.toml"


]

[env]
TERM = 'xterm-256color'

[window]
padding.x = 5
padding.y = 5
dimensions.columns = 130
dimensions.lines = 45 

position.x = 100
position.y = 100
decorations = "Buttonless"
opacity = 0.90

[font]
normal.family = "D2CodingLigature Nerd Font Mono"
size = 16 

[colors]
vi_mode_cursor.text = "CellBackground"
vi_mode_cursor.cursor = "CellForeground"
